// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl2KQplpLXsYb_xhB4CfD22XoBgoIrkNE',
    appId: '1:451320075474:web:b29b5549078bceb64dc90b',
    messagingSenderId: '451320075474',
    projectId: 'lastminutesapp',
    authDomain: 'lastminutesapp.firebaseapp.com',
    storageBucket: 'lastminutesapp.firebasestorage.app',
    measurementId: 'G-B0N2Y28WT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHL_XM6x2Gj69m9n_9o4uXKRBMNHF9h2s',
    appId: '1:451320075474:android:ef9e33dcababf4204dc90b',
    messagingSenderId: '451320075474',
    projectId: 'lastminutesapp',
    storageBucket: 'lastminutesapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgw-yVtMr0pSL3oPQ8eGV6lo04QpL5TZI',
    appId: '1:451320075474:ios:52896d671d21a8254dc90b',
    messagingSenderId: '451320075474',
    projectId: 'lastminutesapp',
    storageBucket: 'lastminutesapp.firebasestorage.app',
    iosBundleId: 'com.example.lastminutesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgw-yVtMr0pSL3oPQ8eGV6lo04QpL5TZI',
    appId: '1:451320075474:ios:52896d671d21a8254dc90b',
    messagingSenderId: '451320075474',
    projectId: 'lastminutesapp',
    storageBucket: 'lastminutesapp.firebasestorage.app',
    iosBundleId: 'com.example.lastminutesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl2KQplpLXsYb_xhB4CfD22XoBgoIrkNE',
    appId: '1:451320075474:web:74564ce95e71f44e4dc90b',
    messagingSenderId: '451320075474',
    projectId: 'lastminutesapp',
    authDomain: 'lastminutesapp.firebaseapp.com',
    storageBucket: 'lastminutesapp.firebasestorage.app',
    measurementId: 'G-L3FRZTGRW1',
  );
}
